package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaPermissao generated by hbm2java
 */
@Entity
@Table(name="ta_permissao"
    ,catalog="bd_sge"
)
public class TaPermissao  implements java.io.Serializable {


     private Integer idtPermissao;
     private TbPerfil tbPerfil;
     private TbUsuario tbUsuario;
     private String usrPermissaoCad;
     private Date dtaPermissaoCad;

    public TaPermissao() {
    }

    public TaPermissao(TbPerfil tbPerfil, TbUsuario tbUsuario, String usrPermissaoCad, Date dtaPermissaoCad) {
       this.tbPerfil = tbPerfil;
       this.tbUsuario = tbUsuario;
       this.usrPermissaoCad = usrPermissaoCad;
       this.dtaPermissaoCad = dtaPermissaoCad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_permissao", unique=true, nullable=false)
    public Integer getIdtPermissao() {
        return this.idtPermissao;
    }
    
    public void setIdtPermissao(Integer idtPermissao) {
        this.idtPermissao = idtPermissao;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_perfil", nullable=false)
    public TbPerfil getTbPerfil() {
        return this.tbPerfil;
    }
    
    public void setTbPerfil(TbPerfil tbPerfil) {
        this.tbPerfil = tbPerfil;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_usuario", nullable=false)
    public TbUsuario getTbUsuario() {
        return this.tbUsuario;
    }
    
    public void setTbUsuario(TbUsuario tbUsuario) {
        this.tbUsuario = tbUsuario;
    }
    
    @Column(name="usr_permissao_cad", nullable=false, length=45)
    public String getUsrPermissaoCad() {
        return this.usrPermissaoCad;
    }
    
    public void setUsrPermissaoCad(String usrPermissaoCad) {
        this.usrPermissaoCad = usrPermissaoCad;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dta_permissao_cad", nullable=false, length=10)
    public Date getDtaPermissaoCad() {
        return this.dtaPermissaoCad;
    }
    
    public void setDtaPermissaoCad(Date dtaPermissaoCad) {
        this.dtaPermissaoCad = dtaPermissaoCad;
    }




}


