package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbAvaliaPelaFaculdade generated by hbm2java
 */
@Entity
@Table(name="tb_avalia_pela_faculdade"
    ,catalog="bd_sge"
)
public class TbAvaliaPelaFaculdade  implements java.io.Serializable {


     private int idtAvaliaPelaFaculdade;
     private TbFaculdade tbFaculdade;
     private TbEstagiario tbEstagiario;
     private int ntaEstagioAvaliaPelaFaculdade;
     private int ntaSupervisaoAvaliaPelaFaculdade;
     private int ntaInfraAvaliaPelaFaculdade;
     private String comAvaliaPelaFaculdade;

    public TbAvaliaPelaFaculdade() {
    }

	
    public TbAvaliaPelaFaculdade(int idtAvaliaPelaFaculdade, TbFaculdade tbFaculdade, TbEstagiario tbEstagiario, int ntaEstagioAvaliaPelaFaculdade, int ntaSupervisaoAvaliaPelaFaculdade, int ntaInfraAvaliaPelaFaculdade) {
        this.idtAvaliaPelaFaculdade = idtAvaliaPelaFaculdade;
        this.tbFaculdade = tbFaculdade;
        this.tbEstagiario = tbEstagiario;
        this.ntaEstagioAvaliaPelaFaculdade = ntaEstagioAvaliaPelaFaculdade;
        this.ntaSupervisaoAvaliaPelaFaculdade = ntaSupervisaoAvaliaPelaFaculdade;
        this.ntaInfraAvaliaPelaFaculdade = ntaInfraAvaliaPelaFaculdade;
    }
    public TbAvaliaPelaFaculdade(int idtAvaliaPelaFaculdade, TbFaculdade tbFaculdade, TbEstagiario tbEstagiario, int ntaEstagioAvaliaPelaFaculdade, int ntaSupervisaoAvaliaPelaFaculdade, int ntaInfraAvaliaPelaFaculdade, String comAvaliaPelaFaculdade) {
       this.idtAvaliaPelaFaculdade = idtAvaliaPelaFaculdade;
       this.tbFaculdade = tbFaculdade;
       this.tbEstagiario = tbEstagiario;
       this.ntaEstagioAvaliaPelaFaculdade = ntaEstagioAvaliaPelaFaculdade;
       this.ntaSupervisaoAvaliaPelaFaculdade = ntaSupervisaoAvaliaPelaFaculdade;
       this.ntaInfraAvaliaPelaFaculdade = ntaInfraAvaliaPelaFaculdade;
       this.comAvaliaPelaFaculdade = comAvaliaPelaFaculdade;
    }
   
     @Id 
    
    @Column(name="idt_avalia_pela_faculdade", unique=true, nullable=false)
    public int getIdtAvaliaPelaFaculdade() {
        return this.idtAvaliaPelaFaculdade;
    }
    
    public void setIdtAvaliaPelaFaculdade(int idtAvaliaPelaFaculdade) {
        this.idtAvaliaPelaFaculdade = idtAvaliaPelaFaculdade;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_faculdade", nullable=false)
    public TbFaculdade getTbFaculdade() {
        return this.tbFaculdade;
    }
    
    public void setTbFaculdade(TbFaculdade tbFaculdade) {
        this.tbFaculdade = tbFaculdade;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_estagiario", nullable=false)
    public TbEstagiario getTbEstagiario() {
        return this.tbEstagiario;
    }
    
    public void setTbEstagiario(TbEstagiario tbEstagiario) {
        this.tbEstagiario = tbEstagiario;
    }
    
    @Column(name="nta_estagio_avalia_pela_faculdade", nullable=false)
    public int getNtaEstagioAvaliaPelaFaculdade() {
        return this.ntaEstagioAvaliaPelaFaculdade;
    }
    
    public void setNtaEstagioAvaliaPelaFaculdade(int ntaEstagioAvaliaPelaFaculdade) {
        this.ntaEstagioAvaliaPelaFaculdade = ntaEstagioAvaliaPelaFaculdade;
    }
    
    @Column(name="nta_supervisao_avalia_pela_faculdade", nullable=false)
    public int getNtaSupervisaoAvaliaPelaFaculdade() {
        return this.ntaSupervisaoAvaliaPelaFaculdade;
    }
    
    public void setNtaSupervisaoAvaliaPelaFaculdade(int ntaSupervisaoAvaliaPelaFaculdade) {
        this.ntaSupervisaoAvaliaPelaFaculdade = ntaSupervisaoAvaliaPelaFaculdade;
    }
    
    @Column(name="nta_infra_avalia_pela_faculdade", nullable=false)
    public int getNtaInfraAvaliaPelaFaculdade() {
        return this.ntaInfraAvaliaPelaFaculdade;
    }
    
    public void setNtaInfraAvaliaPelaFaculdade(int ntaInfraAvaliaPelaFaculdade) {
        this.ntaInfraAvaliaPelaFaculdade = ntaInfraAvaliaPelaFaculdade;
    }
    
    @Column(name="com_avalia_pela_faculdade", length=200)
    public String getComAvaliaPelaFaculdade() {
        return this.comAvaliaPelaFaculdade;
    }
    
    public void setComAvaliaPelaFaculdade(String comAvaliaPelaFaculdade) {
        this.comAvaliaPelaFaculdade = comAvaliaPelaFaculdade;
    }




}


