package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbAvaliaPeloEstagiario generated by hbm2java
 */
@Entity
@Table(name="tb_avalia_pelo_estagiario"
    ,catalog="bd_sge"
)
public class TbAvaliaPeloEstagiario  implements java.io.Serializable {


     private Integer idtAvaliaPeloEstagiario;
     private TbEstagiario tbEstagiario;
     private int ntaOrientadorAvaliaPeloEstagiario;
     private int ntaSupervisorAvaliaPeloEstagiario;
     private int ntaInfraAvaliaPeloEstagiario;
     private String comAvaliaPeloEstagiario;

    public TbAvaliaPeloEstagiario() {
    }

	
    public TbAvaliaPeloEstagiario(TbEstagiario tbEstagiario, int ntaOrientadorAvaliaPeloEstagiario, int ntaSupervisorAvaliaPeloEstagiario, int ntaInfraAvaliaPeloEstagiario) {
        this.tbEstagiario = tbEstagiario;
        this.ntaOrientadorAvaliaPeloEstagiario = ntaOrientadorAvaliaPeloEstagiario;
        this.ntaSupervisorAvaliaPeloEstagiario = ntaSupervisorAvaliaPeloEstagiario;
        this.ntaInfraAvaliaPeloEstagiario = ntaInfraAvaliaPeloEstagiario;
    }
    public TbAvaliaPeloEstagiario(TbEstagiario tbEstagiario, int ntaOrientadorAvaliaPeloEstagiario, int ntaSupervisorAvaliaPeloEstagiario, int ntaInfraAvaliaPeloEstagiario, String comAvaliaPeloEstagiario) {
       this.tbEstagiario = tbEstagiario;
       this.ntaOrientadorAvaliaPeloEstagiario = ntaOrientadorAvaliaPeloEstagiario;
       this.ntaSupervisorAvaliaPeloEstagiario = ntaSupervisorAvaliaPeloEstagiario;
       this.ntaInfraAvaliaPeloEstagiario = ntaInfraAvaliaPeloEstagiario;
       this.comAvaliaPeloEstagiario = comAvaliaPeloEstagiario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_avalia_pelo_estagiario", unique=true, nullable=false)
    public Integer getIdtAvaliaPeloEstagiario() {
        return this.idtAvaliaPeloEstagiario;
    }
    
    public void setIdtAvaliaPeloEstagiario(Integer idtAvaliaPeloEstagiario) {
        this.idtAvaliaPeloEstagiario = idtAvaliaPeloEstagiario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_estagiario", nullable=false)
    public TbEstagiario getTbEstagiario() {
        return this.tbEstagiario;
    }
    
    public void setTbEstagiario(TbEstagiario tbEstagiario) {
        this.tbEstagiario = tbEstagiario;
    }
    
    @Column(name="nta_orientador_avalia_pelo_estagiario", nullable=false)
    public int getNtaOrientadorAvaliaPeloEstagiario() {
        return this.ntaOrientadorAvaliaPeloEstagiario;
    }
    
    public void setNtaOrientadorAvaliaPeloEstagiario(int ntaOrientadorAvaliaPeloEstagiario) {
        this.ntaOrientadorAvaliaPeloEstagiario = ntaOrientadorAvaliaPeloEstagiario;
    }
    
    @Column(name="nta_supervisor_avalia_pelo_estagiario", nullable=false)
    public int getNtaSupervisorAvaliaPeloEstagiario() {
        return this.ntaSupervisorAvaliaPeloEstagiario;
    }
    
    public void setNtaSupervisorAvaliaPeloEstagiario(int ntaSupervisorAvaliaPeloEstagiario) {
        this.ntaSupervisorAvaliaPeloEstagiario = ntaSupervisorAvaliaPeloEstagiario;
    }
    
    @Column(name="nta_infra_avalia_pelo_estagiario", nullable=false)
    public int getNtaInfraAvaliaPeloEstagiario() {
        return this.ntaInfraAvaliaPeloEstagiario;
    }
    
    public void setNtaInfraAvaliaPeloEstagiario(int ntaInfraAvaliaPeloEstagiario) {
        this.ntaInfraAvaliaPeloEstagiario = ntaInfraAvaliaPeloEstagiario;
    }
    
    @Column(name="com_avalia_pelo_estagiario", length=200)
    public String getComAvaliaPeloEstagiario() {
        return this.comAvaliaPeloEstagiario;
    }
    
    public void setComAvaliaPeloEstagiario(String comAvaliaPeloEstagiario) {
        this.comAvaliaPeloEstagiario = comAvaliaPeloEstagiario;
    }




}


