package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbCalendarioAluno generated by hbm2java
 */
@Entity
@Table(name="tb_calendario_aluno"
    ,catalog="bd_sge"
)
public class TbCalendarioAluno  implements java.io.Serializable {


     private Integer idtCalendarioAluno;
     private TbEstagiario tbEstagiario;
     private Date dtaInicialCalendarioAluno;
     private Date dtaFinalCalendarioAluno;

    public TbCalendarioAluno() {
    }

    public TbCalendarioAluno(TbEstagiario tbEstagiario, Date dtaInicialCalendarioAluno, Date dtaFinalCalendarioAluno) {
       this.tbEstagiario = tbEstagiario;
       this.dtaInicialCalendarioAluno = dtaInicialCalendarioAluno;
       this.dtaFinalCalendarioAluno = dtaFinalCalendarioAluno;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_calendario_aluno", unique=true, nullable=false)
    public Integer getIdtCalendarioAluno() {
        return this.idtCalendarioAluno;
    }
    
    public void setIdtCalendarioAluno(Integer idtCalendarioAluno) {
        this.idtCalendarioAluno = idtCalendarioAluno;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_estagiario", nullable=false)
    public TbEstagiario getTbEstagiario() {
        return this.tbEstagiario;
    }
    
    public void setTbEstagiario(TbEstagiario tbEstagiario) {
        this.tbEstagiario = tbEstagiario;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dta_inicial_calendario_aluno", nullable=false, length=10)
    public Date getDtaInicialCalendarioAluno() {
        return this.dtaInicialCalendarioAluno;
    }
    
    public void setDtaInicialCalendarioAluno(Date dtaInicialCalendarioAluno) {
        this.dtaInicialCalendarioAluno = dtaInicialCalendarioAluno;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dta_final_calendario_aluno", nullable=false, length=10)
    public Date getDtaFinalCalendarioAluno() {
        return this.dtaFinalCalendarioAluno;
    }
    
    public void setDtaFinalCalendarioAluno(Date dtaFinalCalendarioAluno) {
        this.dtaFinalCalendarioAluno = dtaFinalCalendarioAluno;
    }




}


