package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbCalendarioGeral generated by hbm2java
 */
@Entity
@Table(name="tb_calendario_geral"
    ,catalog="bd_sge"
)
public class TbCalendarioGeral  implements java.io.Serializable {


     private Integer idtCalendarioGeral;
     private TbVaga tbVaga;
     private Date dtaInicialCalendarioGeral;
     private Date dtaFinalCalendarioGeral;

    public TbCalendarioGeral() {
    }

    public TbCalendarioGeral(TbVaga tbVaga, Date dtaInicialCalendarioGeral, Date dtaFinalCalendarioGeral) {
       this.tbVaga = tbVaga;
       this.dtaInicialCalendarioGeral = dtaInicialCalendarioGeral;
       this.dtaFinalCalendarioGeral = dtaFinalCalendarioGeral;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_calendario_geral", unique=true, nullable=false)
    public Integer getIdtCalendarioGeral() {
        return this.idtCalendarioGeral;
    }
    
    public void setIdtCalendarioGeral(Integer idtCalendarioGeral) {
        this.idtCalendarioGeral = idtCalendarioGeral;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_vaga", nullable=false)
    public TbVaga getTbVaga() {
        return this.tbVaga;
    }
    
    public void setTbVaga(TbVaga tbVaga) {
        this.tbVaga = tbVaga;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dta_inicial_calendario_geral", nullable=false, length=10)
    public Date getDtaInicialCalendarioGeral() {
        return this.dtaInicialCalendarioGeral;
    }
    
    public void setDtaInicialCalendarioGeral(Date dtaInicialCalendarioGeral) {
        this.dtaInicialCalendarioGeral = dtaInicialCalendarioGeral;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dta_final_calendario_geral", nullable=false, length=10)
    public Date getDtaFinalCalendarioGeral() {
        return this.dtaFinalCalendarioGeral;
    }
    
    public void setDtaFinalCalendarioGeral(Date dtaFinalCalendarioGeral) {
        this.dtaFinalCalendarioGeral = dtaFinalCalendarioGeral;
    }




}


