package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbCenario generated by hbm2java
 */
@Entity
@Table(name="tb_cenario"
    ,catalog="bd_sge"
)
public class TbCenario  implements java.io.Serializable {


     private Integer idtCenario;
     private TbMedico tbMedico;
     private TdEspecialidade tdEspecialidade;
     private TbHospital tbHospital;
     private String nmeCenario;
     private String descCenario;
     private Set<TbVaga> tbVagas = new HashSet<TbVaga>(0);
     private Set<TbPreco> tbPrecos = new HashSet<TbPreco>(0);

    public TbCenario() {
    }

	
    public TbCenario(TbMedico tbMedico, TdEspecialidade tdEspecialidade, TbHospital tbHospital, String nmeCenario) {
        this.tbMedico = tbMedico;
        this.tdEspecialidade = tdEspecialidade;
        this.tbHospital = tbHospital;
        this.nmeCenario = nmeCenario;
    }
    public TbCenario(TbMedico tbMedico, TdEspecialidade tdEspecialidade, TbHospital tbHospital, String nmeCenario, String descCenario, Set<TbVaga> tbVagas, Set<TbPreco> tbPrecos) {
       this.tbMedico = tbMedico;
       this.tdEspecialidade = tdEspecialidade;
       this.tbHospital = tbHospital;
       this.nmeCenario = nmeCenario;
       this.descCenario = descCenario;
       this.tbVagas = tbVagas;
       this.tbPrecos = tbPrecos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_cenario", unique=true, nullable=false)
    public Integer getIdtCenario() {
        return this.idtCenario;
    }
    
    public void setIdtCenario(Integer idtCenario) {
        this.idtCenario = idtCenario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_medico", nullable=false)
    public TbMedico getTbMedico() {
        return this.tbMedico;
    }
    
    public void setTbMedico(TbMedico tbMedico) {
        this.tbMedico = tbMedico;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_especialidade", nullable=false)
    public TdEspecialidade getTdEspecialidade() {
        return this.tdEspecialidade;
    }
    
    public void setTdEspecialidade(TdEspecialidade tdEspecialidade) {
        this.tdEspecialidade = tdEspecialidade;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_hospital", nullable=false)
    public TbHospital getTbHospital() {
        return this.tbHospital;
    }
    
    public void setTbHospital(TbHospital tbHospital) {
        this.tbHospital = tbHospital;
    }
    
    @Column(name="nme_cenario", nullable=false, length=50)
    public String getNmeCenario() {
        return this.nmeCenario;
    }
    
    public void setNmeCenario(String nmeCenario) {
        this.nmeCenario = nmeCenario;
    }
    
    @Column(name="desc_cenario", length=500)
    public String getDescCenario() {
        return this.descCenario;
    }
    
    public void setDescCenario(String descCenario) {
        this.descCenario = descCenario;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbCenario")
    public Set<TbVaga> getTbVagas() {
        return this.tbVagas;
    }
    
    public void setTbVagas(Set<TbVaga> tbVagas) {
        this.tbVagas = tbVagas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbCenario")
    public Set<TbPreco> getTbPrecos() {
        return this.tbPrecos;
    }
    
    public void setTbPrecos(Set<TbPreco> tbPrecos) {
        this.tbPrecos = tbPrecos;
    }




}


