package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbEstagiario generated by hbm2java
 */
@Entity
@Table(name="tb_estagiario"
    ,catalog="bd_sge"
)
public class TbEstagiario  implements java.io.Serializable {


     private Integer idtEstagiario;
     private TdRgEstagiario tdRgEstagiario;
     private TbOrientador tbOrientador;
     private TdHorarioExp tdHorarioExp;
     private TbPreco tbPreco;
     private TbPessoa tbPessoa;
     private TbSupEstagio tbSupEstagio;
     private TbFaculdade tbFaculdade;
     private TbVaga tbVaga;
     private String matEstagiario;
     private String histEstagiario;
     private char flgAtivoEstagiario;
     private Set<TbAvaliaPeloEstagiario> tbAvaliaPeloEstagiarios = new HashSet<TbAvaliaPeloEstagiario>(0);
     private Set<TbOcorrencia> tbOcorrencias = new HashSet<TbOcorrencia>(0);
     private Set<TbRelatorio> tbRelatorios = new HashSet<TbRelatorio>(0);
     private Set<TbPlanoAtividade> tbPlanoAtividades = new HashSet<TbPlanoAtividade>(0);
     private Set<TbCalendarioAluno> tbCalendarioAlunos = new HashSet<TbCalendarioAluno>(0);
     private Set<TbAvaliaEstagiario> tbAvaliaEstagiarios = new HashSet<TbAvaliaEstagiario>(0);
     private Set<TbAvaliaPelaFaculdade> tbAvaliaPelaFaculdades = new HashSet<TbAvaliaPelaFaculdade>(0);

    public TbEstagiario() {
    }

	
    public TbEstagiario(TdRgEstagiario tdRgEstagiario, TbOrientador tbOrientador, TdHorarioExp tdHorarioExp, TbPreco tbPreco, TbPessoa tbPessoa, TbSupEstagio tbSupEstagio, TbFaculdade tbFaculdade, TbVaga tbVaga, String matEstagiario, String histEstagiario, char flgAtivoEstagiario) {
        this.tdRgEstagiario = tdRgEstagiario;
        this.tbOrientador = tbOrientador;
        this.tdHorarioExp = tdHorarioExp;
        this.tbPreco = tbPreco;
        this.tbPessoa = tbPessoa;
        this.tbSupEstagio = tbSupEstagio;
        this.tbFaculdade = tbFaculdade;
        this.tbVaga = tbVaga;
        this.matEstagiario = matEstagiario;
        this.histEstagiario = histEstagiario;
        this.flgAtivoEstagiario = flgAtivoEstagiario;
    }
    public TbEstagiario(TdRgEstagiario tdRgEstagiario, TbOrientador tbOrientador, TdHorarioExp tdHorarioExp, TbPreco tbPreco, TbPessoa tbPessoa, TbSupEstagio tbSupEstagio, TbFaculdade tbFaculdade, TbVaga tbVaga, String matEstagiario, String histEstagiario, char flgAtivoEstagiario, Set<TbAvaliaPeloEstagiario> tbAvaliaPeloEstagiarios, Set<TbOcorrencia> tbOcorrencias, Set<TbRelatorio> tbRelatorios, Set<TbPlanoAtividade> tbPlanoAtividades, Set<TbCalendarioAluno> tbCalendarioAlunos, Set<TbAvaliaEstagiario> tbAvaliaEstagiarios, Set<TbAvaliaPelaFaculdade> tbAvaliaPelaFaculdades) {
       this.tdRgEstagiario = tdRgEstagiario;
       this.tbOrientador = tbOrientador;
       this.tdHorarioExp = tdHorarioExp;
       this.tbPreco = tbPreco;
       this.tbPessoa = tbPessoa;
       this.tbSupEstagio = tbSupEstagio;
       this.tbFaculdade = tbFaculdade;
       this.tbVaga = tbVaga;
       this.matEstagiario = matEstagiario;
       this.histEstagiario = histEstagiario;
       this.flgAtivoEstagiario = flgAtivoEstagiario;
       this.tbAvaliaPeloEstagiarios = tbAvaliaPeloEstagiarios;
       this.tbOcorrencias = tbOcorrencias;
       this.tbRelatorios = tbRelatorios;
       this.tbPlanoAtividades = tbPlanoAtividades;
       this.tbCalendarioAlunos = tbCalendarioAlunos;
       this.tbAvaliaEstagiarios = tbAvaliaEstagiarios;
       this.tbAvaliaPelaFaculdades = tbAvaliaPelaFaculdades;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_estagiario", unique=true, nullable=false)
    public Integer getIdtEstagiario() {
        return this.idtEstagiario;
    }
    
    public void setIdtEstagiario(Integer idtEstagiario) {
        this.idtEstagiario = idtEstagiario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_rg_estagiario", nullable=false)
    public TdRgEstagiario getTdRgEstagiario() {
        return this.tdRgEstagiario;
    }
    
    public void setTdRgEstagiario(TdRgEstagiario tdRgEstagiario) {
        this.tdRgEstagiario = tdRgEstagiario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_orientador", nullable=false)
    public TbOrientador getTbOrientador() {
        return this.tbOrientador;
    }
    
    public void setTbOrientador(TbOrientador tbOrientador) {
        this.tbOrientador = tbOrientador;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_horario_exp", nullable=false)
    public TdHorarioExp getTdHorarioExp() {
        return this.tdHorarioExp;
    }
    
    public void setTdHorarioExp(TdHorarioExp tdHorarioExp) {
        this.tdHorarioExp = tdHorarioExp;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_preco", nullable=false)
    public TbPreco getTbPreco() {
        return this.tbPreco;
    }
    
    public void setTbPreco(TbPreco tbPreco) {
        this.tbPreco = tbPreco;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_pessoa", nullable=false)
    public TbPessoa getTbPessoa() {
        return this.tbPessoa;
    }
    
    public void setTbPessoa(TbPessoa tbPessoa) {
        this.tbPessoa = tbPessoa;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_sup_estagio", nullable=false)
    public TbSupEstagio getTbSupEstagio() {
        return this.tbSupEstagio;
    }
    
    public void setTbSupEstagio(TbSupEstagio tbSupEstagio) {
        this.tbSupEstagio = tbSupEstagio;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_faculdade", nullable=false)
    public TbFaculdade getTbFaculdade() {
        return this.tbFaculdade;
    }
    
    public void setTbFaculdade(TbFaculdade tbFaculdade) {
        this.tbFaculdade = tbFaculdade;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_vaga", nullable=false)
    public TbVaga getTbVaga() {
        return this.tbVaga;
    }
    
    public void setTbVaga(TbVaga tbVaga) {
        this.tbVaga = tbVaga;
    }
    
    @Column(name="mat_estagiario", nullable=false, length=15)
    public String getMatEstagiario() {
        return this.matEstagiario;
    }
    
    public void setMatEstagiario(String matEstagiario) {
        this.matEstagiario = matEstagiario;
    }
    
    @Column(name="hist_estagiario", nullable=false, length=100)
    public String getHistEstagiario() {
        return this.histEstagiario;
    }
    
    public void setHistEstagiario(String histEstagiario) {
        this.histEstagiario = histEstagiario;
    }
    
    @Column(name="flg_ativo_estagiario", nullable=false, length=1)
    public char getFlgAtivoEstagiario() {
        return this.flgAtivoEstagiario;
    }
    
    public void setFlgAtivoEstagiario(char flgAtivoEstagiario) {
        this.flgAtivoEstagiario = flgAtivoEstagiario;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbEstagiario")
    public Set<TbAvaliaPeloEstagiario> getTbAvaliaPeloEstagiarios() {
        return this.tbAvaliaPeloEstagiarios;
    }
    
    public void setTbAvaliaPeloEstagiarios(Set<TbAvaliaPeloEstagiario> tbAvaliaPeloEstagiarios) {
        this.tbAvaliaPeloEstagiarios = tbAvaliaPeloEstagiarios;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbEstagiario")
    public Set<TbOcorrencia> getTbOcorrencias() {
        return this.tbOcorrencias;
    }
    
    public void setTbOcorrencias(Set<TbOcorrencia> tbOcorrencias) {
        this.tbOcorrencias = tbOcorrencias;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbEstagiario")
    public Set<TbRelatorio> getTbRelatorios() {
        return this.tbRelatorios;
    }
    
    public void setTbRelatorios(Set<TbRelatorio> tbRelatorios) {
        this.tbRelatorios = tbRelatorios;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbEstagiario")
    public Set<TbPlanoAtividade> getTbPlanoAtividades() {
        return this.tbPlanoAtividades;
    }
    
    public void setTbPlanoAtividades(Set<TbPlanoAtividade> tbPlanoAtividades) {
        this.tbPlanoAtividades = tbPlanoAtividades;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbEstagiario")
    public Set<TbCalendarioAluno> getTbCalendarioAlunos() {
        return this.tbCalendarioAlunos;
    }
    
    public void setTbCalendarioAlunos(Set<TbCalendarioAluno> tbCalendarioAlunos) {
        this.tbCalendarioAlunos = tbCalendarioAlunos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbEstagiario")
    public Set<TbAvaliaEstagiario> getTbAvaliaEstagiarios() {
        return this.tbAvaliaEstagiarios;
    }
    
    public void setTbAvaliaEstagiarios(Set<TbAvaliaEstagiario> tbAvaliaEstagiarios) {
        this.tbAvaliaEstagiarios = tbAvaliaEstagiarios;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbEstagiario")
    public Set<TbAvaliaPelaFaculdade> getTbAvaliaPelaFaculdades() {
        return this.tbAvaliaPelaFaculdades;
    }
    
    public void setTbAvaliaPelaFaculdades(Set<TbAvaliaPelaFaculdade> tbAvaliaPelaFaculdades) {
        this.tbAvaliaPelaFaculdades = tbAvaliaPelaFaculdades;
    }




}


