package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TbFaculdade generated by hbm2java
 */
@Entity
@Table(name="tb_faculdade"
    ,catalog="bd_sge"
    , uniqueConstraints = @UniqueConstraint(columnNames="no_convenio_faculdade") 
)
public class TbFaculdade  implements java.io.Serializable {


     private Integer idtFaculdade;
     private String nmeFaculdade;
     private String sglFaculdade;
     private String endFaculdade;
     private String telFaculdade;
     private String emailFaculdade;
     private String telSecFaculdade;
     private String senhaFaculdade;
     private int noConvenioFaculdade;
     private Date dtaValidadeConvenioFaculdade;
     private Set<TbEstagiario> tbEstagiarios = new HashSet<TbEstagiario>(0);
     private Set<TbOrientador> tbOrientadors = new HashSet<TbOrientador>(0);
     private Set<TbAvaliaPelaFaculdade> tbAvaliaPelaFaculdades = new HashSet<TbAvaliaPelaFaculdade>(0);

    public TbFaculdade() {
    }

	
    public TbFaculdade(String nmeFaculdade, String sglFaculdade, String endFaculdade, String telFaculdade, String emailFaculdade, String senhaFaculdade, int noConvenioFaculdade, Date dtaValidadeConvenioFaculdade) {
        this.nmeFaculdade = nmeFaculdade;
        this.sglFaculdade = sglFaculdade;
        this.endFaculdade = endFaculdade;
        this.telFaculdade = telFaculdade;
        this.emailFaculdade = emailFaculdade;
        this.senhaFaculdade = senhaFaculdade;
        this.noConvenioFaculdade = noConvenioFaculdade;
        this.dtaValidadeConvenioFaculdade = dtaValidadeConvenioFaculdade;
    }
    public TbFaculdade(String nmeFaculdade, String sglFaculdade, String endFaculdade, String telFaculdade, String emailFaculdade, String telSecFaculdade, String senhaFaculdade, int noConvenioFaculdade, Date dtaValidadeConvenioFaculdade, Set<TbEstagiario> tbEstagiarios, Set<TbOrientador> tbOrientadors, Set<TbAvaliaPelaFaculdade> tbAvaliaPelaFaculdades) {
       this.nmeFaculdade = nmeFaculdade;
       this.sglFaculdade = sglFaculdade;
       this.endFaculdade = endFaculdade;
       this.telFaculdade = telFaculdade;
       this.emailFaculdade = emailFaculdade;
       this.telSecFaculdade = telSecFaculdade;
       this.senhaFaculdade = senhaFaculdade;
       this.noConvenioFaculdade = noConvenioFaculdade;
       this.dtaValidadeConvenioFaculdade = dtaValidadeConvenioFaculdade;
       this.tbEstagiarios = tbEstagiarios;
       this.tbOrientadors = tbOrientadors;
       this.tbAvaliaPelaFaculdades = tbAvaliaPelaFaculdades;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_faculdade", unique=true, nullable=false)
    public Integer getIdtFaculdade() {
        return this.idtFaculdade;
    }
    
    public void setIdtFaculdade(Integer idtFaculdade) {
        this.idtFaculdade = idtFaculdade;
    }
    
    @Column(name="nme_faculdade", nullable=false, length=80)
    public String getNmeFaculdade() {
        return this.nmeFaculdade;
    }
    
    public void setNmeFaculdade(String nmeFaculdade) {
        this.nmeFaculdade = nmeFaculdade;
    }
    
    @Column(name="sgl_faculdade", nullable=false, length=15)
    public String getSglFaculdade() {
        return this.sglFaculdade;
    }
    
    public void setSglFaculdade(String sglFaculdade) {
        this.sglFaculdade = sglFaculdade;
    }
    
    @Column(name="end_faculdade", nullable=false, length=100)
    public String getEndFaculdade() {
        return this.endFaculdade;
    }
    
    public void setEndFaculdade(String endFaculdade) {
        this.endFaculdade = endFaculdade;
    }
    
    @Column(name="tel_faculdade", nullable=false, length=20)
    public String getTelFaculdade() {
        return this.telFaculdade;
    }
    
    public void setTelFaculdade(String telFaculdade) {
        this.telFaculdade = telFaculdade;
    }
    
    @Column(name="email_faculdade", nullable=false, length=45)
    public String getEmailFaculdade() {
        return this.emailFaculdade;
    }
    
    public void setEmailFaculdade(String emailFaculdade) {
        this.emailFaculdade = emailFaculdade;
    }
    
    @Column(name="tel_sec_faculdade", length=20)
    public String getTelSecFaculdade() {
        return this.telSecFaculdade;
    }
    
    public void setTelSecFaculdade(String telSecFaculdade) {
        this.telSecFaculdade = telSecFaculdade;
    }
    
    @Column(name="senha_faculdade", nullable=false, length=200)
    public String getSenhaFaculdade() {
        return this.senhaFaculdade;
    }
    
    public void setSenhaFaculdade(String senhaFaculdade) {
        this.senhaFaculdade = senhaFaculdade;
    }
    
    @Column(name="no_convenio_faculdade", unique=true, nullable=false)
    public int getNoConvenioFaculdade() {
        return this.noConvenioFaculdade;
    }
    
    public void setNoConvenioFaculdade(int noConvenioFaculdade) {
        this.noConvenioFaculdade = noConvenioFaculdade;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dta_validade_convenio_faculdade", nullable=false, length=10)
    public Date getDtaValidadeConvenioFaculdade() {
        return this.dtaValidadeConvenioFaculdade;
    }
    
    public void setDtaValidadeConvenioFaculdade(Date dtaValidadeConvenioFaculdade) {
        this.dtaValidadeConvenioFaculdade = dtaValidadeConvenioFaculdade;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbFaculdade")
    public Set<TbEstagiario> getTbEstagiarios() {
        return this.tbEstagiarios;
    }
    
    public void setTbEstagiarios(Set<TbEstagiario> tbEstagiarios) {
        this.tbEstagiarios = tbEstagiarios;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbFaculdade")
    public Set<TbOrientador> getTbOrientadors() {
        return this.tbOrientadors;
    }
    
    public void setTbOrientadors(Set<TbOrientador> tbOrientadors) {
        this.tbOrientadors = tbOrientadors;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbFaculdade")
    public Set<TbAvaliaPelaFaculdade> getTbAvaliaPelaFaculdades() {
        return this.tbAvaliaPelaFaculdades;
    }
    
    public void setTbAvaliaPelaFaculdades(Set<TbAvaliaPelaFaculdade> tbAvaliaPelaFaculdades) {
        this.tbAvaliaPelaFaculdades = tbAvaliaPelaFaculdades;
    }




}


