package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbFuncionarioHosp generated by hbm2java
 */
@Entity
@Table(name="tb_funcionario_hosp"
    ,catalog="bd_sge"
)
public class TbFuncionarioHosp  implements java.io.Serializable {


     private Integer idtFuncionarioHosp;
     private TbPessoa tbPessoa;
     private TbHospital tbHospital;

    public TbFuncionarioHosp() {
    }

    public TbFuncionarioHosp(TbPessoa tbPessoa, TbHospital tbHospital) {
       this.tbPessoa = tbPessoa;
       this.tbHospital = tbHospital;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_funcionario_hosp", unique=true, nullable=false)
    public Integer getIdtFuncionarioHosp() {
        return this.idtFuncionarioHosp;
    }
    
    public void setIdtFuncionarioHosp(Integer idtFuncionarioHosp) {
        this.idtFuncionarioHosp = idtFuncionarioHosp;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_pessoa", nullable=false)
    public TbPessoa getTbPessoa() {
        return this.tbPessoa;
    }
    
    public void setTbPessoa(TbPessoa tbPessoa) {
        this.tbPessoa = tbPessoa;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_hospital", nullable=false)
    public TbHospital getTbHospital() {
        return this.tbHospital;
    }
    
    public void setTbHospital(TbHospital tbHospital) {
        this.tbHospital = tbHospital;
    }




}


