package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbLog generated by hbm2java
 */
@Entity
@Table(name="tb_log"
    ,catalog="bd_sge"
)
public class TbLog  implements java.io.Serializable {


     private Integer idtLog;
     private TbUsuario tbUsuario;
     private String usrLogCad;
     private Date dtLogCad;
     private String descOperacaoLog;
     private Date dtaOperacaoLog;
     private String usrOperacaoLog;

    public TbLog() {
    }

    public TbLog(TbUsuario tbUsuario, String usrLogCad, Date dtLogCad, String descOperacaoLog, Date dtaOperacaoLog, String usrOperacaoLog) {
       this.tbUsuario = tbUsuario;
       this.usrLogCad = usrLogCad;
       this.dtLogCad = dtLogCad;
       this.descOperacaoLog = descOperacaoLog;
       this.dtaOperacaoLog = dtaOperacaoLog;
       this.usrOperacaoLog = usrOperacaoLog;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_log", unique=true, nullable=false)
    public Integer getIdtLog() {
        return this.idtLog;
    }
    
    public void setIdtLog(Integer idtLog) {
        this.idtLog = idtLog;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_usuario", nullable=false)
    public TbUsuario getTbUsuario() {
        return this.tbUsuario;
    }
    
    public void setTbUsuario(TbUsuario tbUsuario) {
        this.tbUsuario = tbUsuario;
    }
    
    @Column(name="usr_log_cad", nullable=false, length=45)
    public String getUsrLogCad() {
        return this.usrLogCad;
    }
    
    public void setUsrLogCad(String usrLogCad) {
        this.usrLogCad = usrLogCad;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dt_log_cad", nullable=false, length=10)
    public Date getDtLogCad() {
        return this.dtLogCad;
    }
    
    public void setDtLogCad(Date dtLogCad) {
        this.dtLogCad = dtLogCad;
    }
    
    @Column(name="desc_operacao_log", nullable=false, length=200)
    public String getDescOperacaoLog() {
        return this.descOperacaoLog;
    }
    
    public void setDescOperacaoLog(String descOperacaoLog) {
        this.descOperacaoLog = descOperacaoLog;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dta_operacao_log", nullable=false, length=10)
    public Date getDtaOperacaoLog() {
        return this.dtaOperacaoLog;
    }
    
    public void setDtaOperacaoLog(Date dtaOperacaoLog) {
        this.dtaOperacaoLog = dtaOperacaoLog;
    }
    
    @Column(name="usr_operacao_log", nullable=false, length=45)
    public String getUsrOperacaoLog() {
        return this.usrOperacaoLog;
    }
    
    public void setUsrOperacaoLog(String usrOperacaoLog) {
        this.usrOperacaoLog = usrOperacaoLog;
    }




}


