package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbMapeamento generated by hbm2java
 */
@Entity
@Table(name="tb_mapeamento"
    ,catalog="bd_sge"
)
public class TbMapeamento  implements java.io.Serializable {


     private Integer idtMapeamento;
     private TbOpcao tbOpcao;
     private String usrMapeamentoCad;
     private Date dtaMapeamentoCad;
     private String nmeMapeamento;
     private String nmeCaminhoClasse;
     private String nmeMetodo;
     private Set<TbPerfil> tbPerfils = new HashSet<TbPerfil>(0);

    public TbMapeamento() {
    }

	
    public TbMapeamento(TbOpcao tbOpcao, String usrMapeamentoCad, Date dtaMapeamentoCad, String nmeMapeamento, String nmeCaminhoClasse, String nmeMetodo) {
        this.tbOpcao = tbOpcao;
        this.usrMapeamentoCad = usrMapeamentoCad;
        this.dtaMapeamentoCad = dtaMapeamentoCad;
        this.nmeMapeamento = nmeMapeamento;
        this.nmeCaminhoClasse = nmeCaminhoClasse;
        this.nmeMetodo = nmeMetodo;
    }
    public TbMapeamento(TbOpcao tbOpcao, String usrMapeamentoCad, Date dtaMapeamentoCad, String nmeMapeamento, String nmeCaminhoClasse, String nmeMetodo, Set<TbPerfil> tbPerfils) {
       this.tbOpcao = tbOpcao;
       this.usrMapeamentoCad = usrMapeamentoCad;
       this.dtaMapeamentoCad = dtaMapeamentoCad;
       this.nmeMapeamento = nmeMapeamento;
       this.nmeCaminhoClasse = nmeCaminhoClasse;
       this.nmeMetodo = nmeMetodo;
       this.tbPerfils = tbPerfils;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_mapeamento", unique=true, nullable=false)
    public Integer getIdtMapeamento() {
        return this.idtMapeamento;
    }
    
    public void setIdtMapeamento(Integer idtMapeamento) {
        this.idtMapeamento = idtMapeamento;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_opcao", nullable=false)
    public TbOpcao getTbOpcao() {
        return this.tbOpcao;
    }
    
    public void setTbOpcao(TbOpcao tbOpcao) {
        this.tbOpcao = tbOpcao;
    }
    
    @Column(name="usr_mapeamento_cad", nullable=false, length=30)
    public String getUsrMapeamentoCad() {
        return this.usrMapeamentoCad;
    }
    
    public void setUsrMapeamentoCad(String usrMapeamentoCad) {
        this.usrMapeamentoCad = usrMapeamentoCad;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dta_mapeamento_cad", nullable=false, length=10)
    public Date getDtaMapeamentoCad() {
        return this.dtaMapeamentoCad;
    }
    
    public void setDtaMapeamentoCad(Date dtaMapeamentoCad) {
        this.dtaMapeamentoCad = dtaMapeamentoCad;
    }
    
    @Column(name="nme_mapeamento", nullable=false, length=200)
    public String getNmeMapeamento() {
        return this.nmeMapeamento;
    }
    
    public void setNmeMapeamento(String nmeMapeamento) {
        this.nmeMapeamento = nmeMapeamento;
    }
    
    @Column(name="nme_caminho_classe", nullable=false, length=200)
    public String getNmeCaminhoClasse() {
        return this.nmeCaminhoClasse;
    }
    
    public void setNmeCaminhoClasse(String nmeCaminhoClasse) {
        this.nmeCaminhoClasse = nmeCaminhoClasse;
    }
    
    @Column(name="nme_metodo", nullable=false, length=45)
    public String getNmeMetodo() {
        return this.nmeMetodo;
    }
    
    public void setNmeMetodo(String nmeMetodo) {
        this.nmeMetodo = nmeMetodo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbMapeamento")
    public Set<TbPerfil> getTbPerfils() {
        return this.tbPerfils;
    }
    
    public void setTbPerfils(Set<TbPerfil> tbPerfils) {
        this.tbPerfils = tbPerfils;
    }




}


