package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbModulo generated by hbm2java
 */
@Entity
@Table(name="tb_modulo"
    ,catalog="bd_sge"
)
public class TbModulo  implements java.io.Serializable {


     private Integer idtModulo;
     private String usrModuloCad;
     private Date dtaModuloCad;
     private String nmeModulo;
     private String descModulo;
     private Set<TbMenu> tbMenus = new HashSet<TbMenu>(0);

    public TbModulo() {
    }

	
    public TbModulo(String usrModuloCad, Date dtaModuloCad, String nmeModulo, String descModulo) {
        this.usrModuloCad = usrModuloCad;
        this.dtaModuloCad = dtaModuloCad;
        this.nmeModulo = nmeModulo;
        this.descModulo = descModulo;
    }
    public TbModulo(String usrModuloCad, Date dtaModuloCad, String nmeModulo, String descModulo, Set<TbMenu> tbMenus) {
       this.usrModuloCad = usrModuloCad;
       this.dtaModuloCad = dtaModuloCad;
       this.nmeModulo = nmeModulo;
       this.descModulo = descModulo;
       this.tbMenus = tbMenus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_modulo", unique=true, nullable=false)
    public Integer getIdtModulo() {
        return this.idtModulo;
    }
    
    public void setIdtModulo(Integer idtModulo) {
        this.idtModulo = idtModulo;
    }
    
    @Column(name="usr_modulo_cad", nullable=false, length=20)
    public String getUsrModuloCad() {
        return this.usrModuloCad;
    }
    
    public void setUsrModuloCad(String usrModuloCad) {
        this.usrModuloCad = usrModuloCad;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dta_modulo_cad", nullable=false, length=10)
    public Date getDtaModuloCad() {
        return this.dtaModuloCad;
    }
    
    public void setDtaModuloCad(Date dtaModuloCad) {
        this.dtaModuloCad = dtaModuloCad;
    }
    
    @Column(name="nme_modulo", nullable=false, length=45)
    public String getNmeModulo() {
        return this.nmeModulo;
    }
    
    public void setNmeModulo(String nmeModulo) {
        this.nmeModulo = nmeModulo;
    }
    
    @Column(name="desc_modulo", nullable=false, length=100)
    public String getDescModulo() {
        return this.descModulo;
    }
    
    public void setDescModulo(String descModulo) {
        this.descModulo = descModulo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbModulo")
    public Set<TbMenu> getTbMenus() {
        return this.tbMenus;
    }
    
    public void setTbMenus(Set<TbMenu> tbMenus) {
        this.tbMenus = tbMenus;
    }




}


