package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbOcorrencia generated by hbm2java
 */
@Entity
@Table(name="tb_ocorrencia"
    ,catalog="bd_sge"
)
public class TbOcorrencia  implements java.io.Serializable {


     private Integer idtOcorrencia;
     private TdTipoOcorrencia tdTipoOcorrencia;
     private TbHospital tbHospital;
     private TbEstagiario tbEstagiario;
     private String descOcorrencia;

    public TbOcorrencia() {
    }

	
    public TbOcorrencia(TdTipoOcorrencia tdTipoOcorrencia, TbHospital tbHospital, String descOcorrencia) {
        this.tdTipoOcorrencia = tdTipoOcorrencia;
        this.tbHospital = tbHospital;
        this.descOcorrencia = descOcorrencia;
    }
    public TbOcorrencia(TdTipoOcorrencia tdTipoOcorrencia, TbHospital tbHospital, TbEstagiario tbEstagiario, String descOcorrencia) {
       this.tdTipoOcorrencia = tdTipoOcorrencia;
       this.tbHospital = tbHospital;
       this.tbEstagiario = tbEstagiario;
       this.descOcorrencia = descOcorrencia;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_ocorrencia", unique=true, nullable=false)
    public Integer getIdtOcorrencia() {
        return this.idtOcorrencia;
    }
    
    public void setIdtOcorrencia(Integer idtOcorrencia) {
        this.idtOcorrencia = idtOcorrencia;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_tipo_ocorrencia", nullable=false)
    public TdTipoOcorrencia getTdTipoOcorrencia() {
        return this.tdTipoOcorrencia;
    }
    
    public void setTdTipoOcorrencia(TdTipoOcorrencia tdTipoOcorrencia) {
        this.tdTipoOcorrencia = tdTipoOcorrencia;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_hospital", nullable=false)
    public TbHospital getTbHospital() {
        return this.tbHospital;
    }
    
    public void setTbHospital(TbHospital tbHospital) {
        this.tbHospital = tbHospital;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_estagiario")
    public TbEstagiario getTbEstagiario() {
        return this.tbEstagiario;
    }
    
    public void setTbEstagiario(TbEstagiario tbEstagiario) {
        this.tbEstagiario = tbEstagiario;
    }
    
    @Column(name="desc_ocorrencia", nullable=false, length=200)
    public String getDescOcorrencia() {
        return this.descOcorrencia;
    }
    
    public void setDescOcorrencia(String descOcorrencia) {
        this.descOcorrencia = descOcorrencia;
    }




}


