package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbPerfil generated by hbm2java
 */
@Entity
@Table(name="tb_perfil"
    ,catalog="bd_sge"
)
public class TbPerfil  implements java.io.Serializable {


     private Integer idtPerfil;
     private TbMapeamento tbMapeamento;
     private String usrPerfilCad;
     private Date dtaPerfilCad;
     private String nmePerfil;
     private String descPerfil;
     private Set<TaPermissao> taPermissaos = new HashSet<TaPermissao>(0);

    public TbPerfil() {
    }

	
    public TbPerfil(TbMapeamento tbMapeamento, String usrPerfilCad, Date dtaPerfilCad, String nmePerfil, String descPerfil) {
        this.tbMapeamento = tbMapeamento;
        this.usrPerfilCad = usrPerfilCad;
        this.dtaPerfilCad = dtaPerfilCad;
        this.nmePerfil = nmePerfil;
        this.descPerfil = descPerfil;
    }
    public TbPerfil(TbMapeamento tbMapeamento, String usrPerfilCad, Date dtaPerfilCad, String nmePerfil, String descPerfil, Set<TaPermissao> taPermissaos) {
       this.tbMapeamento = tbMapeamento;
       this.usrPerfilCad = usrPerfilCad;
       this.dtaPerfilCad = dtaPerfilCad;
       this.nmePerfil = nmePerfil;
       this.descPerfil = descPerfil;
       this.taPermissaos = taPermissaos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_perfil", unique=true, nullable=false)
    public Integer getIdtPerfil() {
        return this.idtPerfil;
    }
    
    public void setIdtPerfil(Integer idtPerfil) {
        this.idtPerfil = idtPerfil;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_mapeamento", nullable=false)
    public TbMapeamento getTbMapeamento() {
        return this.tbMapeamento;
    }
    
    public void setTbMapeamento(TbMapeamento tbMapeamento) {
        this.tbMapeamento = tbMapeamento;
    }
    
    @Column(name="usr_perfil_cad", nullable=false, length=30)
    public String getUsrPerfilCad() {
        return this.usrPerfilCad;
    }
    
    public void setUsrPerfilCad(String usrPerfilCad) {
        this.usrPerfilCad = usrPerfilCad;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dta_perfil_cad", nullable=false, length=10)
    public Date getDtaPerfilCad() {
        return this.dtaPerfilCad;
    }
    
    public void setDtaPerfilCad(Date dtaPerfilCad) {
        this.dtaPerfilCad = dtaPerfilCad;
    }
    
    @Column(name="nme_perfil", nullable=false, length=45)
    public String getNmePerfil() {
        return this.nmePerfil;
    }
    
    public void setNmePerfil(String nmePerfil) {
        this.nmePerfil = nmePerfil;
    }
    
    @Column(name="desc_perfil", nullable=false, length=100)
    public String getDescPerfil() {
        return this.descPerfil;
    }
    
    public void setDescPerfil(String descPerfil) {
        this.descPerfil = descPerfil;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbPerfil")
    public Set<TaPermissao> getTaPermissaos() {
        return this.taPermissaos;
    }
    
    public void setTaPermissaos(Set<TaPermissao> taPermissaos) {
        this.taPermissaos = taPermissaos;
    }




}


