package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbPessoa generated by hbm2java
 */
@Entity
@Table(name="tb_pessoa"
    ,catalog="bd_sge"
)
public class TbPessoa  implements java.io.Serializable {


     private Integer idtPessoa;
     private String nmePessoa;
     private String endPessoa;
     private String cpfPessoa;
     private String telPessoal;
     private String telComercial;
     private Date dtaNascimento;
     private String natuPessoa;
     private Character sexoPessoa;
     private String ftoPessoa;
     private String emailPessoa;
     private Set<TbEstagiario> tbEstagiarios = new HashSet<TbEstagiario>(0);
     private Set<TbFuncionarioSec> tbFuncionarioSecs = new HashSet<TbFuncionarioSec>(0);
     private Set<TbFuncionarioHosp> tbFuncionarioHosps = new HashSet<TbFuncionarioHosp>(0);
     private Set<TbMedico> tbMedicos = new HashSet<TbMedico>(0);
     private Set<TbUsuario> tbUsuarios = new HashSet<TbUsuario>(0);

    public TbPessoa() {
    }

	
    public TbPessoa(String nmePessoa, String endPessoa, String cpfPessoa, String telPessoal, Date dtaNascimento) {
        this.nmePessoa = nmePessoa;
        this.endPessoa = endPessoa;
        this.cpfPessoa = cpfPessoa;
        this.telPessoal = telPessoal;
        this.dtaNascimento = dtaNascimento;
    }
    public TbPessoa(String nmePessoa, String endPessoa, String cpfPessoa, String telPessoal, String telComercial, Date dtaNascimento, String natuPessoa, Character sexoPessoa, String ftoPessoa, String emailPessoa, Set<TbEstagiario> tbEstagiarios, Set<TbFuncionarioSec> tbFuncionarioSecs, Set<TbFuncionarioHosp> tbFuncionarioHosps, Set<TbMedico> tbMedicos, Set<TbUsuario> tbUsuarios) {
       this.nmePessoa = nmePessoa;
       this.endPessoa = endPessoa;
       this.cpfPessoa = cpfPessoa;
       this.telPessoal = telPessoal;
       this.telComercial = telComercial;
       this.dtaNascimento = dtaNascimento;
       this.natuPessoa = natuPessoa;
       this.sexoPessoa = sexoPessoa;
       this.ftoPessoa = ftoPessoa;
       this.emailPessoa = emailPessoa;
       this.tbEstagiarios = tbEstagiarios;
       this.tbFuncionarioSecs = tbFuncionarioSecs;
       this.tbFuncionarioHosps = tbFuncionarioHosps;
       this.tbMedicos = tbMedicos;
       this.tbUsuarios = tbUsuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_pessoa", unique=true, nullable=false)
    public Integer getIdtPessoa() {
        return this.idtPessoa;
    }
    
    public void setIdtPessoa(Integer idtPessoa) {
        this.idtPessoa = idtPessoa;
    }
    
    @Column(name="nme_pessoa", nullable=false, length=80)
    public String getNmePessoa() {
        return this.nmePessoa;
    }
    
    public void setNmePessoa(String nmePessoa) {
        this.nmePessoa = nmePessoa;
    }
    
    @Column(name="end_pessoa", nullable=false, length=100)
    public String getEndPessoa() {
        return this.endPessoa;
    }
    
    public void setEndPessoa(String endPessoa) {
        this.endPessoa = endPessoa;
    }
    
    @Column(name="cpf_pessoa", nullable=false, length=14)
    public String getCpfPessoa() {
        return this.cpfPessoa;
    }
    
    public void setCpfPessoa(String cpfPessoa) {
        this.cpfPessoa = cpfPessoa;
    }
    
    @Column(name="tel_pessoal", nullable=false, length=20)
    public String getTelPessoal() {
        return this.telPessoal;
    }
    
    public void setTelPessoal(String telPessoal) {
        this.telPessoal = telPessoal;
    }
    
    @Column(name="tel_comercial", length=20)
    public String getTelComercial() {
        return this.telComercial;
    }
    
    public void setTelComercial(String telComercial) {
        this.telComercial = telComercial;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dta_nascimento", nullable=false, length=19)
    public Date getDtaNascimento() {
        return this.dtaNascimento;
    }
    
    public void setDtaNascimento(Date dtaNascimento) {
        this.dtaNascimento = dtaNascimento;
    }
    
    @Column(name="natu_pessoa", length=60)
    public String getNatuPessoa() {
        return this.natuPessoa;
    }
    
    public void setNatuPessoa(String natuPessoa) {
        this.natuPessoa = natuPessoa;
    }
    
    @Column(name="sexo_pessoa", length=1)
    public Character getSexoPessoa() {
        return this.sexoPessoa;
    }
    
    public void setSexoPessoa(Character sexoPessoa) {
        this.sexoPessoa = sexoPessoa;
    }
    
    @Column(name="fto_pessoa", length=100)
    public String getFtoPessoa() {
        return this.ftoPessoa;
    }
    
    public void setFtoPessoa(String ftoPessoa) {
        this.ftoPessoa = ftoPessoa;
    }
    
    @Column(name="email_pessoa", length=100)
    public String getEmailPessoa() {
        return this.emailPessoa;
    }
    
    public void setEmailPessoa(String emailPessoa) {
        this.emailPessoa = emailPessoa;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbPessoa")
    public Set<TbEstagiario> getTbEstagiarios() {
        return this.tbEstagiarios;
    }
    
    public void setTbEstagiarios(Set<TbEstagiario> tbEstagiarios) {
        this.tbEstagiarios = tbEstagiarios;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbPessoa")
    public Set<TbFuncionarioSec> getTbFuncionarioSecs() {
        return this.tbFuncionarioSecs;
    }
    
    public void setTbFuncionarioSecs(Set<TbFuncionarioSec> tbFuncionarioSecs) {
        this.tbFuncionarioSecs = tbFuncionarioSecs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbPessoa")
    public Set<TbFuncionarioHosp> getTbFuncionarioHosps() {
        return this.tbFuncionarioHosps;
    }
    
    public void setTbFuncionarioHosps(Set<TbFuncionarioHosp> tbFuncionarioHosps) {
        this.tbFuncionarioHosps = tbFuncionarioHosps;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbPessoa")
    public Set<TbMedico> getTbMedicos() {
        return this.tbMedicos;
    }
    
    public void setTbMedicos(Set<TbMedico> tbMedicos) {
        this.tbMedicos = tbMedicos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbPessoa")
    public Set<TbUsuario> getTbUsuarios() {
        return this.tbUsuarios;
    }
    
    public void setTbUsuarios(Set<TbUsuario> tbUsuarios) {
        this.tbUsuarios = tbUsuarios;
    }




}


