package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbPlanoAtividade generated by hbm2java
 */
@Entity
@Table(name="tb_plano_atividade"
    ,catalog="bd_sge"
)
public class TbPlanoAtividade  implements java.io.Serializable {


     private Integer idtPlanoAtividade;
     private TbSupEstagio tbSupEstagio;
     private TbEstagiario tbEstagiario;
     private String nmePlanoAtividade;
     private Date prdIniPlanoAtividade;
     private String descPlanoAtividade;
     private String statusPlanoAtividade;
     private Date prdFimPlanoAtividade;

    public TbPlanoAtividade() {
    }

	
    public TbPlanoAtividade(TbSupEstagio tbSupEstagio, TbEstagiario tbEstagiario, String nmePlanoAtividade, Date prdIniPlanoAtividade, String descPlanoAtividade, String statusPlanoAtividade) {
        this.tbSupEstagio = tbSupEstagio;
        this.tbEstagiario = tbEstagiario;
        this.nmePlanoAtividade = nmePlanoAtividade;
        this.prdIniPlanoAtividade = prdIniPlanoAtividade;
        this.descPlanoAtividade = descPlanoAtividade;
        this.statusPlanoAtividade = statusPlanoAtividade;
    }
    public TbPlanoAtividade(TbSupEstagio tbSupEstagio, TbEstagiario tbEstagiario, String nmePlanoAtividade, Date prdIniPlanoAtividade, String descPlanoAtividade, String statusPlanoAtividade, Date prdFimPlanoAtividade) {
       this.tbSupEstagio = tbSupEstagio;
       this.tbEstagiario = tbEstagiario;
       this.nmePlanoAtividade = nmePlanoAtividade;
       this.prdIniPlanoAtividade = prdIniPlanoAtividade;
       this.descPlanoAtividade = descPlanoAtividade;
       this.statusPlanoAtividade = statusPlanoAtividade;
       this.prdFimPlanoAtividade = prdFimPlanoAtividade;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_plano_atividade", unique=true, nullable=false)
    public Integer getIdtPlanoAtividade() {
        return this.idtPlanoAtividade;
    }
    
    public void setIdtPlanoAtividade(Integer idtPlanoAtividade) {
        this.idtPlanoAtividade = idtPlanoAtividade;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_sup_estagio", nullable=false)
    public TbSupEstagio getTbSupEstagio() {
        return this.tbSupEstagio;
    }
    
    public void setTbSupEstagio(TbSupEstagio tbSupEstagio) {
        this.tbSupEstagio = tbSupEstagio;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_estagiario", nullable=false)
    public TbEstagiario getTbEstagiario() {
        return this.tbEstagiario;
    }
    
    public void setTbEstagiario(TbEstagiario tbEstagiario) {
        this.tbEstagiario = tbEstagiario;
    }
    
    @Column(name="nme_plano_atividade", nullable=false, length=45)
    public String getNmePlanoAtividade() {
        return this.nmePlanoAtividade;
    }
    
    public void setNmePlanoAtividade(String nmePlanoAtividade) {
        this.nmePlanoAtividade = nmePlanoAtividade;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="prd_ini_plano_atividade", nullable=false, length=10)
    public Date getPrdIniPlanoAtividade() {
        return this.prdIniPlanoAtividade;
    }
    
    public void setPrdIniPlanoAtividade(Date prdIniPlanoAtividade) {
        this.prdIniPlanoAtividade = prdIniPlanoAtividade;
    }
    
    @Column(name="desc_plano_atividade", nullable=false, length=450)
    public String getDescPlanoAtividade() {
        return this.descPlanoAtividade;
    }
    
    public void setDescPlanoAtividade(String descPlanoAtividade) {
        this.descPlanoAtividade = descPlanoAtividade;
    }
    
    @Column(name="status_plano_atividade", nullable=false, length=15)
    public String getStatusPlanoAtividade() {
        return this.statusPlanoAtividade;
    }
    
    public void setStatusPlanoAtividade(String statusPlanoAtividade) {
        this.statusPlanoAtividade = statusPlanoAtividade;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="prd_fim_plano_atividade", length=10)
    public Date getPrdFimPlanoAtividade() {
        return this.prdFimPlanoAtividade;
    }
    
    public void setPrdFimPlanoAtividade(Date prdFimPlanoAtividade) {
        this.prdFimPlanoAtividade = prdFimPlanoAtividade;
    }




}


