package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbPreco generated by hbm2java
 */
@Entity
@Table(name="tb_preco"
    ,catalog="bd_sge"
)
public class TbPreco  implements java.io.Serializable {


     private Integer idtPreco;
     private TbCenario tbCenario;
     private BigDecimal valorPreco;
     private Date dtaValidadePreco;
     private Set<TbEstagiario> tbEstagiarios = new HashSet<TbEstagiario>(0);

    public TbPreco() {
    }

	
    public TbPreco(TbCenario tbCenario, BigDecimal valorPreco, Date dtaValidadePreco) {
        this.tbCenario = tbCenario;
        this.valorPreco = valorPreco;
        this.dtaValidadePreco = dtaValidadePreco;
    }
    public TbPreco(TbCenario tbCenario, BigDecimal valorPreco, Date dtaValidadePreco, Set<TbEstagiario> tbEstagiarios) {
       this.tbCenario = tbCenario;
       this.valorPreco = valorPreco;
       this.dtaValidadePreco = dtaValidadePreco;
       this.tbEstagiarios = tbEstagiarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_preco", unique=true, nullable=false)
    public Integer getIdtPreco() {
        return this.idtPreco;
    }
    
    public void setIdtPreco(Integer idtPreco) {
        this.idtPreco = idtPreco;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_cenario", nullable=false)
    public TbCenario getTbCenario() {
        return this.tbCenario;
    }
    
    public void setTbCenario(TbCenario tbCenario) {
        this.tbCenario = tbCenario;
    }
    
    @Column(name="valor_preco", nullable=false, precision=3)
    public BigDecimal getValorPreco() {
        return this.valorPreco;
    }
    
    public void setValorPreco(BigDecimal valorPreco) {
        this.valorPreco = valorPreco;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dta_validade_preco", nullable=false, length=10)
    public Date getDtaValidadePreco() {
        return this.dtaValidadePreco;
    }
    
    public void setDtaValidadePreco(Date dtaValidadePreco) {
        this.dtaValidadePreco = dtaValidadePreco;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbPreco")
    public Set<TbEstagiario> getTbEstagiarios() {
        return this.tbEstagiarios;
    }
    
    public void setTbEstagiarios(Set<TbEstagiario> tbEstagiarios) {
        this.tbEstagiarios = tbEstagiarios;
    }




}


