package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbRelatorio generated by hbm2java
 */
@Entity
@Table(name="tb_relatorio"
    ,catalog="bd_sge"
)
public class TbRelatorio  implements java.io.Serializable {


     private Integer idtRelatorio;
     private TbHospital tbHospital;
     private TbEstagiario tbEstagiario;
     private String nmeRelatorio;

    public TbRelatorio() {
    }

    public TbRelatorio(TbHospital tbHospital, TbEstagiario tbEstagiario, String nmeRelatorio) {
       this.tbHospital = tbHospital;
       this.tbEstagiario = tbEstagiario;
       this.nmeRelatorio = nmeRelatorio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_relatorio", unique=true, nullable=false)
    public Integer getIdtRelatorio() {
        return this.idtRelatorio;
    }
    
    public void setIdtRelatorio(Integer idtRelatorio) {
        this.idtRelatorio = idtRelatorio;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_hospital", nullable=false)
    public TbHospital getTbHospital() {
        return this.tbHospital;
    }
    
    public void setTbHospital(TbHospital tbHospital) {
        this.tbHospital = tbHospital;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_estagiario", nullable=false)
    public TbEstagiario getTbEstagiario() {
        return this.tbEstagiario;
    }
    
    public void setTbEstagiario(TbEstagiario tbEstagiario) {
        this.tbEstagiario = tbEstagiario;
    }
    
    @Column(name="nme_relatorio", nullable=false, length=45)
    public String getNmeRelatorio() {
        return this.nmeRelatorio;
    }
    
    public void setNmeRelatorio(String nmeRelatorio) {
        this.nmeRelatorio = nmeRelatorio;
    }




}


