package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbSecretariaSaude generated by hbm2java
 */
@Entity
@Table(name="tb_secretaria_saude"
    ,catalog="bd_sge"
)
public class TbSecretariaSaude  implements java.io.Serializable {


     private Integer idtSecretariaSaude;
     private Set<TbHospital> tbHospitals = new HashSet<TbHospital>(0);
     private Set<TbFuncionarioSec> tbFuncionarioSecs = new HashSet<TbFuncionarioSec>(0);

    public TbSecretariaSaude() {
    }

    public TbSecretariaSaude(Set<TbHospital> tbHospitals, Set<TbFuncionarioSec> tbFuncionarioSecs) {
       this.tbHospitals = tbHospitals;
       this.tbFuncionarioSecs = tbFuncionarioSecs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_secretaria_saude", unique=true, nullable=false)
    public Integer getIdtSecretariaSaude() {
        return this.idtSecretariaSaude;
    }
    
    public void setIdtSecretariaSaude(Integer idtSecretariaSaude) {
        this.idtSecretariaSaude = idtSecretariaSaude;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbSecretariaSaude")
    public Set<TbHospital> getTbHospitals() {
        return this.tbHospitals;
    }
    
    public void setTbHospitals(Set<TbHospital> tbHospitals) {
        this.tbHospitals = tbHospitals;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbSecretariaSaude")
    public Set<TbFuncionarioSec> getTbFuncionarioSecs() {
        return this.tbFuncionarioSecs;
    }
    
    public void setTbFuncionarioSecs(Set<TbFuncionarioSec> tbFuncionarioSecs) {
        this.tbFuncionarioSecs = tbFuncionarioSecs;
    }




}


