package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbSupEstagio generated by hbm2java
 */
@Entity
@Table(name="tb_sup_estagio"
    ,catalog="bd_sge"
)
public class TbSupEstagio  implements java.io.Serializable {


     private Integer idtSupEstagio;
     private TbMedico tbMedico;
     private String matSupEstagio;
     private Set<TbPlanoAtividade> tbPlanoAtividades = new HashSet<TbPlanoAtividade>(0);
     private Set<TbEstagiario> tbEstagiarios = new HashSet<TbEstagiario>(0);
     private Set<TbAvaliaEstagiario> tbAvaliaEstagiarios = new HashSet<TbAvaliaEstagiario>(0);

    public TbSupEstagio() {
    }

	
    public TbSupEstagio(TbMedico tbMedico, String matSupEstagio) {
        this.tbMedico = tbMedico;
        this.matSupEstagio = matSupEstagio;
    }
    public TbSupEstagio(TbMedico tbMedico, String matSupEstagio, Set<TbPlanoAtividade> tbPlanoAtividades, Set<TbEstagiario> tbEstagiarios, Set<TbAvaliaEstagiario> tbAvaliaEstagiarios) {
       this.tbMedico = tbMedico;
       this.matSupEstagio = matSupEstagio;
       this.tbPlanoAtividades = tbPlanoAtividades;
       this.tbEstagiarios = tbEstagiarios;
       this.tbAvaliaEstagiarios = tbAvaliaEstagiarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_sup_estagio", unique=true, nullable=false)
    public Integer getIdtSupEstagio() {
        return this.idtSupEstagio;
    }
    
    public void setIdtSupEstagio(Integer idtSupEstagio) {
        this.idtSupEstagio = idtSupEstagio;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_medico", nullable=false)
    public TbMedico getTbMedico() {
        return this.tbMedico;
    }
    
    public void setTbMedico(TbMedico tbMedico) {
        this.tbMedico = tbMedico;
    }
    
    @Column(name="mat_sup_estagio", nullable=false, length=80)
    public String getMatSupEstagio() {
        return this.matSupEstagio;
    }
    
    public void setMatSupEstagio(String matSupEstagio) {
        this.matSupEstagio = matSupEstagio;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbSupEstagio")
    public Set<TbPlanoAtividade> getTbPlanoAtividades() {
        return this.tbPlanoAtividades;
    }
    
    public void setTbPlanoAtividades(Set<TbPlanoAtividade> tbPlanoAtividades) {
        this.tbPlanoAtividades = tbPlanoAtividades;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbSupEstagio")
    public Set<TbEstagiario> getTbEstagiarios() {
        return this.tbEstagiarios;
    }
    
    public void setTbEstagiarios(Set<TbEstagiario> tbEstagiarios) {
        this.tbEstagiarios = tbEstagiarios;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbSupEstagio")
    public Set<TbAvaliaEstagiario> getTbAvaliaEstagiarios() {
        return this.tbAvaliaEstagiarios;
    }
    
    public void setTbAvaliaEstagiarios(Set<TbAvaliaEstagiario> tbAvaliaEstagiarios) {
        this.tbAvaliaEstagiarios = tbAvaliaEstagiarios;
    }




}


