package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbUsuario generated by hbm2java
 */
@Entity
@Table(name="tb_usuario"
    ,catalog="bd_sge"
)
public class TbUsuario  implements java.io.Serializable {


     private Integer idtUsuario;
     private TbPessoa tbPessoa;
     private String usrUsuarioCad;
     private Date dtaUsuarioCad;
     private String loginUsuario;
     private String senhaUsuario;
     private Set<TaPermissao> taPermissaos = new HashSet<TaPermissao>(0);
     private Set<TbLog> tbLogs = new HashSet<TbLog>(0);

    public TbUsuario() {
    }

	
    public TbUsuario(TbPessoa tbPessoa, String usrUsuarioCad, Date dtaUsuarioCad, String loginUsuario, String senhaUsuario) {
        this.tbPessoa = tbPessoa;
        this.usrUsuarioCad = usrUsuarioCad;
        this.dtaUsuarioCad = dtaUsuarioCad;
        this.loginUsuario = loginUsuario;
        this.senhaUsuario = senhaUsuario;
    }
    public TbUsuario(TbPessoa tbPessoa, String usrUsuarioCad, Date dtaUsuarioCad, String loginUsuario, String senhaUsuario, Set<TaPermissao> taPermissaos, Set<TbLog> tbLogs) {
       this.tbPessoa = tbPessoa;
       this.usrUsuarioCad = usrUsuarioCad;
       this.dtaUsuarioCad = dtaUsuarioCad;
       this.loginUsuario = loginUsuario;
       this.senhaUsuario = senhaUsuario;
       this.taPermissaos = taPermissaos;
       this.tbLogs = tbLogs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_usuario", unique=true, nullable=false)
    public Integer getIdtUsuario() {
        return this.idtUsuario;
    }
    
    public void setIdtUsuario(Integer idtUsuario) {
        this.idtUsuario = idtUsuario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_pessoa", nullable=false)
    public TbPessoa getTbPessoa() {
        return this.tbPessoa;
    }
    
    public void setTbPessoa(TbPessoa tbPessoa) {
        this.tbPessoa = tbPessoa;
    }
    
    @Column(name="usr_usuario_cad", nullable=false, length=45)
    public String getUsrUsuarioCad() {
        return this.usrUsuarioCad;
    }
    
    public void setUsrUsuarioCad(String usrUsuarioCad) {
        this.usrUsuarioCad = usrUsuarioCad;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dta_usuario_cad", nullable=false, length=10)
    public Date getDtaUsuarioCad() {
        return this.dtaUsuarioCad;
    }
    
    public void setDtaUsuarioCad(Date dtaUsuarioCad) {
        this.dtaUsuarioCad = dtaUsuarioCad;
    }
    
    @Column(name="login_usuario", nullable=false, length=45)
    public String getLoginUsuario() {
        return this.loginUsuario;
    }
    
    public void setLoginUsuario(String loginUsuario) {
        this.loginUsuario = loginUsuario;
    }
    
    @Column(name="senha_usuario", nullable=false, length=300)
    public String getSenhaUsuario() {
        return this.senhaUsuario;
    }
    
    public void setSenhaUsuario(String senhaUsuario) {
        this.senhaUsuario = senhaUsuario;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbUsuario")
    public Set<TaPermissao> getTaPermissaos() {
        return this.taPermissaos;
    }
    
    public void setTaPermissaos(Set<TaPermissao> taPermissaos) {
        this.taPermissaos = taPermissaos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbUsuario")
    public Set<TbLog> getTbLogs() {
        return this.tbLogs;
    }
    
    public void setTbLogs(Set<TbLog> tbLogs) {
        this.tbLogs = tbLogs;
    }




}


