package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbVaga generated by hbm2java
 */
@Entity
@Table(name="tb_vaga"
    ,catalog="bd_sge"
)
public class TbVaga  implements java.io.Serializable {


     private Integer idtVaga;
     private TbCenario tbCenario;
     private String nmeVaga;
     private Set<TbEstagiario> tbEstagiarios = new HashSet<TbEstagiario>(0);
     private Set<TbCalendarioGeral> tbCalendarioGerals = new HashSet<TbCalendarioGeral>(0);

    public TbVaga() {
    }

	
    public TbVaga(TbCenario tbCenario, String nmeVaga) {
        this.tbCenario = tbCenario;
        this.nmeVaga = nmeVaga;
    }
    public TbVaga(TbCenario tbCenario, String nmeVaga, Set<TbEstagiario> tbEstagiarios, Set<TbCalendarioGeral> tbCalendarioGerals) {
       this.tbCenario = tbCenario;
       this.nmeVaga = nmeVaga;
       this.tbEstagiarios = tbEstagiarios;
       this.tbCalendarioGerals = tbCalendarioGerals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_vaga", unique=true, nullable=false)
    public Integer getIdtVaga() {
        return this.idtVaga;
    }
    
    public void setIdtVaga(Integer idtVaga) {
        this.idtVaga = idtVaga;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_cenario", nullable=false)
    public TbCenario getTbCenario() {
        return this.tbCenario;
    }
    
    public void setTbCenario(TbCenario tbCenario) {
        this.tbCenario = tbCenario;
    }
    
    @Column(name="nme_vaga", nullable=false, length=80)
    public String getNmeVaga() {
        return this.nmeVaga;
    }
    
    public void setNmeVaga(String nmeVaga) {
        this.nmeVaga = nmeVaga;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbVaga")
    public Set<TbEstagiario> getTbEstagiarios() {
        return this.tbEstagiarios;
    }
    
    public void setTbEstagiarios(Set<TbEstagiario> tbEstagiarios) {
        this.tbEstagiarios = tbEstagiarios;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbVaga")
    public Set<TbCalendarioGeral> getTbCalendarioGerals() {
        return this.tbCalendarioGerals;
    }
    
    public void setTbCalendarioGerals(Set<TbCalendarioGeral> tbCalendarioGerals) {
        this.tbCalendarioGerals = tbCalendarioGerals;
    }




}


