package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TdEspecialidade generated by hbm2java
 */
@Entity
@Table(name="td_especialidade"
    ,catalog="bd_sge"
)
public class TdEspecialidade  implements java.io.Serializable {


     private int idtEspecialidade;
     private String nmeEspecialidade;
     private String descEspecialidade;
     private Set<TbCenario> tbCenarios = new HashSet<TbCenario>(0);

    public TdEspecialidade() {
    }

	
    public TdEspecialidade(int idtEspecialidade, String nmeEspecialidade) {
        this.idtEspecialidade = idtEspecialidade;
        this.nmeEspecialidade = nmeEspecialidade;
    }
    public TdEspecialidade(int idtEspecialidade, String nmeEspecialidade, String descEspecialidade, Set<TbCenario> tbCenarios) {
       this.idtEspecialidade = idtEspecialidade;
       this.nmeEspecialidade = nmeEspecialidade;
       this.descEspecialidade = descEspecialidade;
       this.tbCenarios = tbCenarios;
    }
   
     @Id 
    
    @Column(name="idt_especialidade", unique=true, nullable=false)
    public int getIdtEspecialidade() {
        return this.idtEspecialidade;
    }
    
    public void setIdtEspecialidade(int idtEspecialidade) {
        this.idtEspecialidade = idtEspecialidade;
    }
    
    @Column(name="nme_especialidade", nullable=false, length=30)
    public String getNmeEspecialidade() {
        return this.nmeEspecialidade;
    }
    
    public void setNmeEspecialidade(String nmeEspecialidade) {
        this.nmeEspecialidade = nmeEspecialidade;
    }
    
    @Column(name="desc_especialidade", length=400)
    public String getDescEspecialidade() {
        return this.descEspecialidade;
    }
    
    public void setDescEspecialidade(String descEspecialidade) {
        this.descEspecialidade = descEspecialidade;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tdEspecialidade")
    public Set<TbCenario> getTbCenarios() {
        return this.tbCenarios;
    }
    
    public void setTbCenarios(Set<TbCenario> tbCenarios) {
        this.tbCenarios = tbCenarios;
    }




}


