package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TdHorarioExp generated by hbm2java
 */
@Entity
@Table(name="td_horario_exp"
    ,catalog="bd_sge"
)
public class TdHorarioExp  implements java.io.Serializable {


     private Integer idtHorarioExp;
     private String hrIniHorarioExp;
     private String hrFimHorarioExp;
     private Set<TbEstagiario> tbEstagiarios = new HashSet<TbEstagiario>(0);

    public TdHorarioExp() {
    }

	
    public TdHorarioExp(String hrIniHorarioExp, String hrFimHorarioExp) {
        this.hrIniHorarioExp = hrIniHorarioExp;
        this.hrFimHorarioExp = hrFimHorarioExp;
    }
    public TdHorarioExp(String hrIniHorarioExp, String hrFimHorarioExp, Set<TbEstagiario> tbEstagiarios) {
       this.hrIniHorarioExp = hrIniHorarioExp;
       this.hrFimHorarioExp = hrFimHorarioExp;
       this.tbEstagiarios = tbEstagiarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_horario_exp", unique=true, nullable=false)
    public Integer getIdtHorarioExp() {
        return this.idtHorarioExp;
    }
    
    public void setIdtHorarioExp(Integer idtHorarioExp) {
        this.idtHorarioExp = idtHorarioExp;
    }
    
    @Column(name="hr_ini_horario_exp", nullable=false, length=45)
    public String getHrIniHorarioExp() {
        return this.hrIniHorarioExp;
    }
    
    public void setHrIniHorarioExp(String hrIniHorarioExp) {
        this.hrIniHorarioExp = hrIniHorarioExp;
    }
    
    @Column(name="hr_fim_horario_exp", nullable=false, length=45)
    public String getHrFimHorarioExp() {
        return this.hrFimHorarioExp;
    }
    
    public void setHrFimHorarioExp(String hrFimHorarioExp) {
        this.hrFimHorarioExp = hrFimHorarioExp;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tdHorarioExp")
    public Set<TbEstagiario> getTbEstagiarios() {
        return this.tbEstagiarios;
    }
    
    public void setTbEstagiarios(Set<TbEstagiario> tbEstagiarios) {
        this.tbEstagiarios = tbEstagiarios;
    }




}


