package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TdRgEstagiario generated by hbm2java
 */
@Entity
@Table(name="td_rg_estagiario"
    ,catalog="bd_sge"
    , uniqueConstraints = @UniqueConstraint(columnNames="num_rg_estagiario") 
)
public class TdRgEstagiario  implements java.io.Serializable {


     private Integer idtRgEstagiario;
     private int numRgEstagiario;
     private String dtaExpEstagiario;
     private String orgExpEstagiario;
     private Set<TbEstagiario> tbEstagiarios = new HashSet<TbEstagiario>(0);

    public TdRgEstagiario() {
    }

	
    public TdRgEstagiario(int numRgEstagiario, String dtaExpEstagiario, String orgExpEstagiario) {
        this.numRgEstagiario = numRgEstagiario;
        this.dtaExpEstagiario = dtaExpEstagiario;
        this.orgExpEstagiario = orgExpEstagiario;
    }
    public TdRgEstagiario(int numRgEstagiario, String dtaExpEstagiario, String orgExpEstagiario, Set<TbEstagiario> tbEstagiarios) {
       this.numRgEstagiario = numRgEstagiario;
       this.dtaExpEstagiario = dtaExpEstagiario;
       this.orgExpEstagiario = orgExpEstagiario;
       this.tbEstagiarios = tbEstagiarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_rg_estagiario", unique=true, nullable=false)
    public Integer getIdtRgEstagiario() {
        return this.idtRgEstagiario;
    }
    
    public void setIdtRgEstagiario(Integer idtRgEstagiario) {
        this.idtRgEstagiario = idtRgEstagiario;
    }
    
    @Column(name="num_rg_estagiario", unique=true, nullable=false)
    public int getNumRgEstagiario() {
        return this.numRgEstagiario;
    }
    
    public void setNumRgEstagiario(int numRgEstagiario) {
        this.numRgEstagiario = numRgEstagiario;
    }
    
    @Column(name="dta_exp_estagiario", nullable=false, length=45)
    public String getDtaExpEstagiario() {
        return this.dtaExpEstagiario;
    }
    
    public void setDtaExpEstagiario(String dtaExpEstagiario) {
        this.dtaExpEstagiario = dtaExpEstagiario;
    }
    
    @Column(name="org_exp_estagiario", nullable=false, length=45)
    public String getOrgExpEstagiario() {
        return this.orgExpEstagiario;
    }
    
    public void setOrgExpEstagiario(String orgExpEstagiario) {
        this.orgExpEstagiario = orgExpEstagiario;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tdRgEstagiario")
    public Set<TbEstagiario> getTbEstagiarios() {
        return this.tbEstagiarios;
    }
    
    public void setTbEstagiarios(Set<TbEstagiario> tbEstagiarios) {
        this.tbEstagiarios = tbEstagiarios;
    }




}


