package model;
// Generated 23/09/2015 18:27:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TdTipoOcorrencia generated by hbm2java
 */
@Entity
@Table(name="td_tipo_ocorrencia"
    ,catalog="bd_sge"
)
public class TdTipoOcorrencia  implements java.io.Serializable {


     private Integer idtTipoOcorrencia;
     private String nmeTipoOcorrencia;
     private String sglTipoOcorrencia;
     private Set<TbOcorrencia> tbOcorrencias = new HashSet<TbOcorrencia>(0);

    public TdTipoOcorrencia() {
    }

	
    public TdTipoOcorrencia(String nmeTipoOcorrencia, String sglTipoOcorrencia) {
        this.nmeTipoOcorrencia = nmeTipoOcorrencia;
        this.sglTipoOcorrencia = sglTipoOcorrencia;
    }
    public TdTipoOcorrencia(String nmeTipoOcorrencia, String sglTipoOcorrencia, Set<TbOcorrencia> tbOcorrencias) {
       this.nmeTipoOcorrencia = nmeTipoOcorrencia;
       this.sglTipoOcorrencia = sglTipoOcorrencia;
       this.tbOcorrencias = tbOcorrencias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_tipo_ocorrencia", unique=true, nullable=false)
    public Integer getIdtTipoOcorrencia() {
        return this.idtTipoOcorrencia;
    }
    
    public void setIdtTipoOcorrencia(Integer idtTipoOcorrencia) {
        this.idtTipoOcorrencia = idtTipoOcorrencia;
    }
    
    @Column(name="nme_tipo_ocorrencia", nullable=false, length=10)
    public String getNmeTipoOcorrencia() {
        return this.nmeTipoOcorrencia;
    }
    
    public void setNmeTipoOcorrencia(String nmeTipoOcorrencia) {
        this.nmeTipoOcorrencia = nmeTipoOcorrencia;
    }
    
    @Column(name="sgl_tipo_ocorrencia", nullable=false, length=1)
    public String getSglTipoOcorrencia() {
        return this.sglTipoOcorrencia;
    }
    
    public void setSglTipoOcorrencia(String sglTipoOcorrencia) {
        this.sglTipoOcorrencia = sglTipoOcorrencia;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tdTipoOcorrencia")
    public Set<TbOcorrencia> getTbOcorrencias() {
        return this.tbOcorrencias;
    }
    
    public void setTbOcorrencias(Set<TbOcorrencia> tbOcorrencias) {
        this.tbOcorrencias = tbOcorrencias;
    }




}


